
language: node_js
node_js: stable
    
before_install:
- git config --global user.name "sasswen"
- git config --global user.email "962041678@qq.com"

#安装hexo及插件
install:
- npm install

#清除 生成
script:
  - npm run build:pro

after_success:
- cd ./dist
- git init
# 添加自己的项目
- git remote add origin git@github.com:sasswen/gitPartice.git
# 新建并切换分支
- git checkout --orphan source
- git add -A
- git commit -m "Travis CI"
- git push
