
language: node_js
node_js: stable

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

    
#安装hexo及插件
install:
  - npm install  

#清除 生成
script:
  - hexo clean  
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name 

 "username"
  - git config user.email "useremail"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF 

}" master:master
  #- git push --force --quiet "https://${GH_TOKEN}@$ 

{你得项目地址(如果源码跟发布的不在一个分支 这里是分发布用的分支地址)，不带https}" master:master

#默认一个分支可以忽略此配置--监视github仓库中的master分支，分支出现变化就执行build
#branches:
#  only:
#    - master

#build以后的地址
env:
 global:
   - GH_REF: (分发布用的分支地址)  //讲道理 这个地方我还不太清楚有什么用 有知道的可以告诉我下
