
language: node_js
node_js: stable

branches:
  only:
  - master
    
before_install:
- npm install -g npm@8.12.0
- git config --global user.name "sasswen"
- git config --global user.email "962041678@qq.com"
- npm install -g hexo-cli

#安装hexo及插件
install:
- npm install

#清除 生成
script:
- npm run build:pro
